---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-rt"
      include_role:
        name: "ansible-role-rt"
      vars:
        __rt_debug: true
        rt_version: "5.0.1"
        # We're only taking this so far...
        rt_initialize_database: false
