---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v3.2.0"
  hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: detect-private-key
      exclude: ^molecule
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

- repo: https://github.com/ansible/ansible-lint.git
  rev: "v6.8.6"
  hooks:
    - id: ansible-lint

- repo: https://gitlab.com/devopshq/gitlab-ci-linter
  rev: v1.0.4
  hooks:
    - id: gitlab-ci-linter
