---
- name: Install RT SiteConfig(s)
  ansible.builtin.template:
    src: RT_SiteConfig.pm.j2
    dest: "{{ __rt_siteconfig.dest }}"
    owner: root
    group: "{{ rt_web_group }}"
    mode: "0660"
    validate: "perl -c %s"
  vars:
    rt_siteconfig: "{{ __rt_siteconfig.content }}"
  no_log: "{{ rt_no_log }}"
  notify:
    - "rt restart webserver"
