---
# tasks file for ansible-role-rt
- name: Test for an existing RT installation
  stat:
    path: "{{ rt_prefix }}/etc/RT_Config.pm"
  register: __rt_config_st

- name: Create the dest dir
  file:
    path: "{{ rt_prefix }}/lib"
    mode: "0755"
    state: directory
  when:
    - "not __rt_config_st.stat.exists|bool"

- name: Create the RT etc dir
  file:
    path: "{{ rt_prefix }}/etc"
    mode: "0755"
    state: directory
  when:
    - "not __rt_config_st.stat.exists|bool"

- name: (Pre)-Configure the RT instance
  include_tasks: configure_rt.yml
  no_log: "{{ rt_no_log }}"
  loop: "{{ rt_siteconfigs }}"
  loop_control:
    loop_var: __rt_siteconfig

- name: Warn about cpan locallib setting on CentOS 7
  fail:
    msg: >-
      The `rt_cpan_locallib` value isn't respected on CentOS 7. Set that value
      to null on this platform in order to continue.
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version|int == 7"
    - "rt_cpan_locallib is not none"

- name: Install extra CPAN modules (CentOS 7)
  command: >-
    cpan {% if (__cm.notest | default('false')) %}-f{% endif %}
      {{ __cm.author }}/{{ __cm.name | replace('::', '-') }}-{{ __cm.version }}.tar.gz
  environment:
    PERL5LIB: "{{ _rt_perl5lib }}"
  loop: "{{ _rt_cpan_modules }}"
  loop_control:
    loop_var: __cm
  when:
    - "ansible_distribution in ['CentOS']"
    - "ansible_distribution_major_version|int == 7"

- name: Install any extra cpan modules
  cpanm:
    name: "{{ __cm.name }}"
    locallib: "{{ rt_cpan_locallib | default(omit) }}"
    version: "{{ __cm.version }}"
    notest: "{{ __cm.notest | default('false') }}"
  environment:
    PERL5LIB: "{{ _rt_perl5lib }}"
  loop: "{{ _rt_cpan_modules }}"
  loop_control:
    loop_var: __cm
  when:
    - >-
      (ansible_distribution not in ['CentOS'])
      or (ansible_distribution_major_version|int != 7)

- block:
    - name: Create a tempdir
      tempfile:
        state: directory
      changed_when: false
      register: tmpdir

    - name: Download RT
      unarchive:
        src: "{{ _rt_download_url }}"
        dest: "{{ tmpdir.path }}/"
        remote_src: true

    - name: Configure RT
      command: "./configure --prefix {{ rt_prefix  }} {{ rt_configure_options | join(' ') }}"
      environment:
        PERL5LIB: "{{ _rt_perl5lib }}"
      args:
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"

    # On CentOS 7, PERL5LIB is meaningless, since we're just letting CPAN
    # install into the system path.
    - name: Make fixdeps (w/o cpanm)
      make:
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"
        target: fixdeps
      environment:
        AUTOMATED_TESTING: true
        NONINTERACTIVE_TESTING: true
        PERL_MM_USE_DEFAULT: 1
        PERL5LIB: "{{ _rt_perl5lib }}"
      when:
        - >-
          (
            (ansible_distribution == 'CentOS')
            and (ansible_distribution_major_version|int == 7)
          )
          or (rt_cpanm_binpath is none)

    - name: Make fixdeps (cpanm)
      make:
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"
        target: fixdeps
      environment:
        AUTOMATED_TESTING: true
        NONINTERACTIVE_TESTING: true
        PERL_MM_USE_DEFAULT: 1
        PERL5LIB: "{{ _rt_perl5lib }}"
        RT_FIX_DEPS_CMD: "{{ rt_cpanm_binpath }}"
      when:
        - >-
          (ansible_distribution != 'CentOS')
          or (ansible_distribution_major_version|int != 7)
        - "rt_cpanm_binpath is not none"

    - name: Make testdeps
      make:
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"
        target: testdeps
      environment:
        AUTOMATED_TESTING: true
        PERL_MM_USE_DEFAULT: 1
        PERL5LIB: "{{ _rt_perl5lib }}"
      when:
        - "rt_make_testdeps|bool"

    - name: Make install
      make:
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"
        target: install
      environment:
        PERL5LIB: "{{ _rt_perl5lib }}"
      notify:
        - "rt restart webserver"

    - name: Make initialize-database
      command:
      args:
        cmd: sbin/rt-setup-database --action init
        chdir: "{{ tmpdir.path }}/rt-{{ rt_version }}"
      environment:
        AUTOMATED_TESTING: true
        PERL_MM_USE_DEFAULT: 1
        PERL5LIB: "{{ _rt_perl5lib }}"
        RT_DBA_USER: "{{ rt_dba_user }}"
        RT_DBA_PASSWORD: "{{ rt_dba_password }}"
      no_log: "{{ rt_no_log }}"
      notify:
        - "rt restart webserver"
      when:
        - "rt_initialize_database"
  always:
    - name: Clean out tmpdir
      file:
        path: "{{ tmpdir.path }}"
        state: absent
      changed_when: false
      when:
        - "not __rt_debug | default(false)"
  when:
    - "not __rt_config_st.stat.exists|bool"
