---
# handlers file for ansible-role-rt
- name: Restart the webserver
  service:
    name: "{{ rt_webserver_service_name }}"
    state: "{{ rt_webserver_service_restarted_state }}"
  listen: "rt restart webserver"
  when:
    - "rt_webserver_service_restarted_state is not none"
