---
# handlers file for ansible-role-rt
- name: Restart the webserver
  ansible.builtin.service:
    name: "{{ rt_webserver_service_name }}"
    state: "{{ rt_webserver_service_restarted_state }}"
  listen: "rt restart webserver"
  when:
    - "rt_webserver_service_restarted_state is not none"
    - "'molecule-converge-test' is not in ansible_run_tags"
