---
- name: Converge
  hosts: all
  tasks:
    - set_fact:
        _site_content: |
          Set($rtname, "localhost");
          Set($Organization, "test.ca");
          Set($CorrespondAddress, "rt");
          Set($CommentAddress, "rt-comment");
          Set($WebDomain, "localhost");
          Set($WebPort, 443);
          Set($WebPath, "");
          Set($Timezone, "America/Vancouver");
          Set($DatabaseType, {{ _database_driver | quote }});
          Set($DatabaseHost,   {{ _database_hostname | quote }});
          Set($DatabaseRTHost, "localhost");
          Set($DatabasePort, "");
          Set($DatabaseUser, {{ _database_user | default('rt') | quote }});
          Set($DatabasePassword, {{ _database_password | default('rt123') | quote }});
          Set($DatabaseName, {{ _database_name | quote }});
          Set($DatabaseRequireSSL, 1);
          Set($LogToSyslog, "warning");
          Set($LogStackTraces, 1);

    - name: "Include ansible-role-rt"
      include_role:
        name: "ansible-role-rt"
      vars:
        __rt_debug: true
        rt_no_log: false
        rt_dba_user: "{{ _database_admin_user }}"
        rt_dba_password: "{{ _database_admin_password }}"
        rt_siteconfigs:
          - dest: /opt/rt/etc/RT_SiteConfig.pm
            content: "{{ _site_content }}"
